# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        :path => 'server.sh',
	:dfile => home + '/VirtualBox VMs/sata2.vdi',
	:size => 2048,
	:port => 1
    },
    :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
        :path => 'client.sh'
    }, 
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s 
            box.vm.network "private_network", ip: boxconfig[:ip_addr]  
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "512"]
                needsController = false
            if  boxname.to_s.eql? "server"
		unless File.exists?(boxconfig[:dfile])
			vb.customize ['createhd', '--filename', boxconfig[:dfile], '--variant', 'Fixed', '--size', boxconfig[:size]]
                        needsController =  true	
			puts "NEEDSCONTROLLER"
	        end
 	    if needsController == true
	    vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
	    vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', boxconfig[:port], '--device', 0, '--type', 'hdd', '--medium', boxconfig[:dfile]]
	    puts "ATTACH"
	    end
	    end
	    end
            box.vm.provision "shell", inline: <<-SHELL
            	mkdir -p ~root/.ssh
            	cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
           # box.vm.provision "shell", path: boxconfig[:path]
        end
    end
end
