---
 - name: Install MySQL
   yum:
     name: mariadb-server-5.5.68-1.el7
     state: present


 - name: Start MySQL Service
   ansible.builtin.systemd:
     state: started
     enabled: yes
     name: mariadb


 - name: Install Mysql python for ansible
   yum:
     name: MySQL-python
     state: installed
   notify: set root password


 - name: Set MySQL root Password
   mysql_user:
     login_host: 'localhost'
     login_user: 'root'
     login_password: ''
     name: 'root'
     password: 'pass1'
     state: present
