---
 - name: Install MySQL
   yum: 
     name: mariadb-server-5.5.68-1.el7 
     state: present


 - name: Start MySQL Service
   ansible.builtin.systemd:
     state: started 
     enabled: yes
     name: mariadb


 - name: Install Mysql python for ansible
   yum:
     name: MySQL-python
     state: installed


 - name: Create WordPress Database
   mysql_db:
     login_host: localhost
     login_user: root
     name: "{{ wp_db_name }}"
     state: present


 - name: Create WordPress database user
   mysql_user:
     login_host: localhost
     name: "{{ wp_db_user }}"
     password: "{{ wp_db_password }}"
     priv: "{{ wp_db_name }}.*:ALL"
     host: "{{ wp_server_ip }}"
     state: present
