---
 - name: Create WordPress Database
   mysql_db:
     login_host: localhost
     login_user: root
     login_password: "{{ mysql_root_password  }}"
     name: "{{ wp_db_name }}"
     state: present


 - name: Create WordPress database user
   mysql_user:
     login_host: localhost
     login_user: root
     login_password: "{{ mysql_root_password  }}"
     name: "{{ wp_db_user }}"
     password: "{{ wp_db_password }}"
     priv: "{{ wp_db_name }}.*:ALL"
     host: "{{ wp_server_ip }}"
     state: present
