---
 - name: Create Zabbix Database
   mysql_db:
     login_host: 'localhost'
     login_user: root
     login_password: "{{ mysql_root_password  }}"
     name: "{{ zabbix_db_name }}"
     encoding: utf8
     collation: utf8_bin
     state: present


 - name: Create Zabbix database user
   mysql_user:
     login_host: 'localhost'
     login_user: 'root'
     login_password: "{{ mysql_root_password  }}"
     name: "{{ zabbix_db_user }}"
     password: "{{ zabbix_db_password }}"
     priv: "{{ zabbix_db_name }}.*:ALL"
     host: "{{ zabbix_server_ip }}"
     state: present

