---
 - name: Install epel-release
   yum:
     name: epel-release
     state: latest

 - name: Install borgbackup
   yum: 
     name: borgbackup
     state: present


 - name: Copy script .service .timer


 - name: enable timer
