# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :prometheus => {
        :box_name => "centos/7",
        :ip_addr => '1.0.3.192',
        :path => 'script.sh'
    },
#    :client => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.11.102',
#        :path => 'client.sh'
#    }, 
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s  
           # box.vm.network "public_network", bridge: "ens192" #, ip: boxconfig[:ip_addr]  
            box.vm.network "forwarded_port", guest: 9090, host: 9091
            box.vm.network "forwarded_port", guest: 3000, host: 9092
	    box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
                needsController = false
            end
            box.vm.provision "shell", inline: <<-SHELL
            	mkdir -p ~root/.ssh
            	cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
            box.vm.provision "shell", path: boxconfig[:path]
        end
    end
end
