---
 - name: Check if rsyslog installed
   yum:
     name: rsyslog
     state: present

 - name: Copy rsyslog config
   copy:
     src: rsyslog.conf
     dest: /etc/rsyslog.conf
   notify:
     - restart rsyslog 

 
 - name: Copy log naming config
   copy:
     src: remote.conf
     dest: /etc/rsyslog.d/remote.conf
   notify:
     - restart rsyslog

