---
 - name: Check rsyslog 
   yum: 
     name: rsyslog
     state: present

 - name: Check rsyslog daemon
   service:
     name: rsyslog
     state: started
     enabled: yes

 - name: Copy rsyslog config
   template:
     src: rsyslog.conf.j2
     dest: /etc/rsyslog.conf
   notify:
     - restart rsyslog
