# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        :path => 'scripts/log_vm.sh',
	:rsync => 'log'
    },
    :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
        :path => 'scripts/web_vm.sh'
	:rsync => 'web'
    }, 
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.synced_folder boxconfig[:rsync], "/vagrant", type: "rsync"
	    box.vm.host_name = boxname.to_s  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]  
	    box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
                needsController = false
            end
            box.vm.provision "shell", inline: <<-SHELL
            	mkdir -p ~root/.ssh
            	cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
#            box.vm.provision "shell", path: boxconfig[:path]
        end
    end
end
