# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.10.10', adapter: 2, netmask: "255.255.255.0"},
                   {ip: '192.168.20.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "dmz"},
                   {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "intranet"},

                ]
  },
  :mysqlServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.30.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "intranet"},
		]
  },
  :wordpressServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.20.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz"},
                  # {ip: '192.168.10.20', adapter: 3, netmask: "255.255.255.0"},
		]
  },
  :backupsServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.30.5', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "intranet"},
                ]
  },
  :zabbixServer => {
        :box_name => "centos/8",
        :net => [
                   {ip: '192.168.40.10', adapter: 3, netmask: "255.255.255.0"},
                   {ip: '192.168.30.4', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "intranet"},
                ]
  },
#  :nginxServer => {
#        :box_name => "centos/7",
#        :net => [
#                   {ip: '192.168.20.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz"},
#                ]
#  },
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
	  box.vm.synced_folder ".", "/vagrant", type: "rsync"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            #echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            #echo "GATEWAY=192.168.10.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            #systemctl restart network
           # ip route add default via 192.168.10.1
            SHELL
        when "zabbixServer"
		box.vm.provider "virtualbox" do |vb|
            	vb.memory = "1024"
            	end
          box.vm.provision "shell", run: "always", inline: <<-SHELL
	    SHELL
        when "wordpressServer"
	   box.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
           end
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.30.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            ip route add default via 192.168.30.1
	    SHELL
	end
      end
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
   # ansible.verbose = "v"
  end
end
