---
 - name: Install epel-release
   yum:
     name: epel-release
     state: latest

 - name: Install borgbackup
   yum:
     name: borgbackup
     state: present


 - name: Copy backup script 
   template:
     src: borgbackup.sh.j2
     dest: "{{ path_to_backup_script }}"
     mode: '0740'


 - name: Copy borg-backup.service
   template:
     src: borg-backup.service.j2
     dest: /etc/systemd/system/borg-backup.service


 - name: Copy borg-backup.timer
   template:
     src: borg-backup.timer.j2
     dest: /etc/systemd/system/borg-backup.timer

 - name: Enable borg-backup.timer
   systemd:
     name: borg-backup.timer
     state: started
     enabled: yes
