---
 - name: restart MySQL
   ansible.builtin.systemd:
     state: restarted
     name: mariadb


 - name: Set MySQL root Password
   mysql_user:
     login_host: 'localhost'
     login_user: 'root'
     login_password: ''
     name: 'root'
     password: '{{ mysql_root_password }}'
     state: present


 - name: restart rsyslog
   service: 
     name: rsyslog
     state: restarted
