---
 - name: Install epel-release
   yum:
     name: epel-release
     state: latest

 - name: Install nginx
   yum:
     name: nginx-1.16.1-3.el7
     state: present
   notify: start nginx


 - name: Copy nginx configuration for wordpress
   template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
   notify:
     - create self-signed certificate
     - restart nginx
