---
 - name: restart nginx
   ansible.builtin.systemd:
     state: restarted
     enabled: yes
     name: nginx


 - name: create self-signed certificate
   command: >
        openssl req -x509 -nodes -subj '/' -days 365
        -newkey rsa:2048 -sha256 -keyout {{ key_path }} -out {{ cert_path }}
