# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
:inetRouter2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.254.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"},
                   {ip: '192.168.10.10', adapter: 3, netmask: "255.255.255.0"},
		]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.254.2', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"},
		]
  },
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
	    ip route add 192.168.0.0/16 via 192.168.255.2
# скопировать таблицу /etc/sysconfig/iptables
# install iptables iptables-services
# daemon-reload
# restart
# copy knock on centralRouter
            SHELL
        when "inetRouter2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
        #    ip route add 192.168.0.0/16 via 192.168.255.2
            ip route delete default
	    ip route add default via 192.168.10.10
	    ip route add 192.168.0.0/16 via 192.168.254.2
	    iptables -t nat -A PREROUTING -i eth2 -p tcp --dport 8080 -j DNAT --to 192.168.0.2
	    iptables -t nat -A POSTROUTING  -p tcp --dst 192.168.0.2 --dport 80 -j SNAT --to-source 192.168.254.1
	    SHELL
	when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo sysctl net.ipv4.conf.all.forwarding=1
	    sysctl net.ipv4.conf.all.forwarding=1
            echo "net.ipv4.conf.all.forwarding=1" > /etc/sysctl.d/10-net.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
	    systemctl restart network
	    ip route add 192.168.0.0/28 via 192.168.0.1
	    ip route delete default
	    ip route add default via 192.168.255.1
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
	    #echo "DEFROUTE=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            ip route delete default 
            ip route add default via 192.168.0.1
	    yum install -y epel-release
	    yum install -y nginx
	    systemctl start nginx
            SHELL
	end
      end
  end
end
